-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.10.0.111.2
-- Module  Version: 5.8
--/usr/local/diamond/3.10_x64/ispfpga/bin/lin64/scuba -w -n ddrx1 -lang vhdl -synth synplify -bus_exp 7 -bb -arch xo2c00 -type iol -mode in -io_type LVDS25 -width 1 -freq_in 378 -gear 1 -clk dqs -aligned -del 32 

-- Wed Jul 31 17:22:54 2019

library IEEE;
use IEEE.std_logic_1164.all;
-- synopsys translate_off
library MACHXO2;
use MACHXO2.all;
-- synopsys translate_on

entity ddrx1 is
    port (
        clk: in  std_logic; 
        freeze: in  std_logic; 
        lock: out  std_logic; 
        reset: in  std_logic; 
        sclk: out  std_logic; 
        uddcntln: in  std_logic; 
        datain: in  std_logic_vector(0 downto 0); 
        q: out  std_logic_vector(1 downto 0));
end ddrx1;

architecture Structure of ddrx1 is

    -- internal signal declarations
    signal qb0: std_logic;
    signal qa0: std_logic;
    signal dqsdel: std_logic;
    signal sclk_t: std_logic;
    signal dataini_t0: std_logic;
    signal buf_clk: std_logic;
    signal buf_dataini0: std_logic;

    -- local component declarations
    component IB
        port (I: in  std_logic; O: out  std_logic);
    end component;
    component IDDRXE
        port (D: in  std_logic; SCLK: in  std_logic; RST: in  std_logic; 
            Q0: out  std_logic; Q1: out  std_logic);
    end component;
    component DQSDLLC
        generic (FORCE_MAX_DELAY : in String; FIN : in String; 
                LOCK_SENSITIVITY : in String);
        port (CLK: in  std_logic; RST: in  std_logic; 
            UDDCNTLN: in  std_logic; FREEZE: in  std_logic; 
            LOCK: out  std_logic; DQSDEL: out  std_logic);
    end component;
    component DELAYE
        generic (DEL_VALUE : in String; DEL_MODE : in String);
        port (A: in  std_logic; Z: out  std_logic);
    end component;
    component DLLDELC
        port (CLKI: in  std_logic; DQSDEL: in  std_logic; 
            CLKO: out  std_logic);
    end component;
    attribute IO_TYPE : string; 
    attribute IO_TYPE of Inst2_IB : label is "LVDS25";
    attribute IO_TYPE of Inst1_IB0 : label is "LVDS25";
    attribute syn_keep : boolean;
    attribute NGD_DRC_MASK : integer;
    attribute NGD_DRC_MASK of Structure : architecture is 1;

begin
    -- component instantiation statements
    Inst5_IDDRXE0: IDDRXE
        port map (D=>dataini_t0, SCLK=>sclk_t, RST=>reset, Q0=>qa0, 
            Q1=>qb0);

    Inst4_DLLDELC: DLLDELC
        port map (CLKI=>buf_clk, DQSDEL=>dqsdel, CLKO=>sclk_t);

    Inst3_DQSDLLC: DQSDLLC
        generic map (FORCE_MAX_DELAY=> "NO", FIN=> "375.0", 
        LOCK_SENSITIVITY=> "LOW")
        port map (CLK=>sclk_t, RST=>reset, UDDCNTLN=>uddcntln, 
            FREEZE=>freeze, LOCK=>lock, DQSDEL=>dqsdel);

    udel_dataini0: DELAYE
        generic map (DEL_VALUE=> "DELAY0", DEL_MODE=> "SCLK_ALIGNED")
        port map (A=>buf_dataini0, Z=>dataini_t0);

    Inst2_IB: IB
        port map (I=>clk, O=>buf_clk);

    Inst1_IB0: IB
        port map (I=>datain(0), O=>buf_dataini0);

    sclk <= sclk_t;
    q(1) <= qb0;
    q(0) <= qa0;
end Structure;

-- synopsys translate_off
library MACHXO2;
configuration Structure_CON of ddrx1 is
    for Structure
        for all:IB use entity MACHXO2.IB(V); end for;
        for all:IDDRXE use entity MACHXO2.IDDRXE(V); end for;
        for all:DQSDLLC use entity MACHXO2.DQSDLLC(V); end for;
        for all:DELAYE use entity MACHXO2.DELAYE(V); end for;
        for all:DLLDELC use entity MACHXO2.DLLDELC(V); end for;
    end for;
end Structure_CON;

-- synopsys translate_on
